### PR TITLE
Enhancement: Create Laravel application

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] creates a Laravel application 

💁‍♂️ For reference, see https://bootcamp.laravel.com.

### CODE REVIEW

**Comment by szepeviktor** [comment]
What is this a hash of? `88bdda90b0b852d7f40f3d29d49c9fea`

**Comment by localheinz** [comment]
@szepeviktor 

`laravel-application-template`

**Comment by szepeviktor** [comment]
EditorConfig needs
```ini
[*.xml]
indent_size = 2
```
Az XML files are indented with 2 spaces.

**Comment by localheinz** [comment]
@szepeviktor 

I have adjusted the indentation in `.phive/phars.xml`.

Since I generate `psalm-baseline.xml`, I do not care so much about its indentation.

**Pull request merged**
